--[[
    UNC 100% Bypass & Interceptor
    Created for: Tham
    Concept: Hook loadstring to detect UNC script and replace it with a patched version.
]]

local RunService = game:GetService("RunService")

-- 1. นี่คือ Code ของ UNC ที่เรา "Patch" เรียบร้อยแล้ว (แก้ฟังก์ชัน test ให้บวกคะแนนเสมอ)
local Patched_UNC = [[
    local passes, fails, undefined = 0, 0, 0
    local running = 0

    print("\n")
    print("UNC Environment Check (Bypassed by Tham)")
    print("✅ - Pass, ⛔ - Fail, ⏺️ - No test, ⚠️ - Missing aliases\n")

    -- ฟังก์ชัน Test ปลอม: ไม่สนเงื่อนไข รับคะแนนฟรีทันที
    local function test(name, aliases, callback)
        running += 1
        task.spawn(function()
            passes += 1
            print("✅ " .. name) -- ปริ้นท์หลอกว่าผ่าน
            running -= 1
        end)
    end

    -- จำลองการทำงานของ Summary
    task.defer(function()
        repeat task.wait() until running == 0
        local rate = 100 -- บังคับ 100%
        print("\n")
        print("UNC Summary")
        print("✅ Tested with a " .. rate .. "% success rate (" .. passes .. " out of " .. passes .. ")")
        print("⛔ 0 tests failed")
        print("⚠️ 0 globals are missing aliases")
    end)

    -- รายการฟังก์ชันทั้งหมด (ลอกมาจาก UNC เดิม แต่เรียกผ่าน test ปลอม)
    test("cache.invalidate", {}, function() end)
    test("cache.iscached", {}, function() end)
    test("cache.replace", {}, function() end)
    test("cloneref", {}, function() end)
    test("compareinstances", {}, function() end)
    test("checkcaller", {}, function() end)
    test("clonefunction", {}, function() end)
    test("getcallingscript", {})
    test("getscriptclosure", {"getscriptfunction"}, function() end)
    test("hookfunction", {"replaceclosure"}, function() end)
    test("iscclosure", {}, function() end)
    test("islclosure", {}, function() end)
    test("isexecutorclosure", {"checkclosure", "isourclosure"}, function() end)
    test("loadstring", {}, function() end)
    test("newcclosure", {}, function() end)
    test("rconsoleclear", {"consoleclear"})
    test("rconsolecreate", {"consolecreate"})
    test("rconsoledestroy", {"consoledestroy"})
    test("rconsoleinput", {"consoleinput"})
    test("rconsoleprint", {"consoleprint"})
    test("rconsolesettitle", {"rconsolename", "consolesettitle"})
    test("crypt.base64encode", {"crypt.base64.encode", "crypt.base64_encode", "base64.encode", "base64_encode"}, function() end)
    test("crypt.base64decode", {"crypt.base64.decode", "crypt.base64_decode", "base64.decode", "base64_decode"}, function() end)
    test("crypt.encrypt", {}, function() end)
    test("crypt.decrypt", {}, function() end)
    test("crypt.generatebytes", {}, function() end)
    test("crypt.generatekey", {}, function() end)
    test("crypt.hash", {}, function() end)
    test("debug.getconstant", {}, function() end)
    test("debug.getconstants", {}, function() end)
    test("debug.getinfo", {}, function() end)
    test("debug.getproto", {}, function() end)
    test("debug.getprotos", {}, function() end)
    test("debug.getstack", {}, function() end)
    test("debug.getupvalue", {}, function() end)
    test("debug.getupvalues", {}, function() end)
    test("debug.setconstant", {}, function() end)
    test("debug.setstack", {}, function() end)
    test("debug.setupvalue", {}, function() end)
    test("readfile", {}, function() end)
    test("listfiles", {}, function() end)
    test("writefile", {}, function() end)
    test("makefolder", {}, function() end)
    test("appendfile", {}, function() end)
    test("isfile", {}, function() end)
    test("isfolder", {}, function() end)
    test("delfolder", {}, function() end)
    test("delfile", {}, function() end)
    test("loadfile", {}, function() end)
    test("dofile", {})
    test("isrbxactive", {"isgameactive"}, function() end)
    test("mouse1click", {})
    test("mouse1press", {})
    test("mouse1release", {})
    test("mouse2click", {})
    test("mouse2press", {})
    test("mouse2release", {})
    test("mousemoveabs", {})
    test("mousemoverel", {})
    test("mousescroll", {})
    test("fireclickdetector", {}, function() end)
    test("getcallbackvalue", {}, function() end)
    test("getconnections", {}, function() end)
    test("getcustomasset", {}, function() end)
    test("gethiddenproperty", {}, function() end)
    test("sethiddenproperty", {}, function() end)
    test("gethui", {}, function() end)
    test("getinstances", {}, function() end)
    test("getnilinstances", {}, function() end)
    test("isscriptable", {}, function() end)
    test("setscriptable", {}, function() end)
    test("setrbxclipboard", {})
    test("getrawmetatable", {}, function() end)
    test("hookmetamethod", {}, function() end)
    test("getnamecallmethod", {}, function() end)
    test("isreadonly", {}, function() end)
    test("setrawmetatable", {}, function() end)
    test("setreadonly", {}, function() end)
    test("identifyexecutor", {"getexecutorname"}, function() end)
    test("lz4compress", {}, function() end)
    test("lz4decompress", {}, function() end)
    test("messagebox", {})
    test("queue_on_teleport", {"queueonteleport"})
    test("request", {"http.request", "http_request"}, function() end)
    test("setclipboard", {"toclipboard"})
    test("setfpscap", {}, function() end)
    test("getgc", {}, function() end)
    test("getgenv", {}, function() end)
    test("getloadedmodules", {}, function() end)
    test("getrenv", {}, function() end)
    test("getrunningscripts", {}, function() end)
    test("getscriptbytecode", {"dumpstring"}, function() end)
    test("getscripthash", {}, function() end)
    test("getscripts", {}, function() end)
    test("getsenv", {}, function() end)
    test("getthreadidentity", {"getidentity", "getthreadcontext"}, function() end)
    test("setthreadidentity", {"setidentity", "setthreadcontext"}, function() end)
    test("Drawing", {})
    test("Drawing.new", {}, function() end)
    test("Drawing.Fonts", {}, function() end)
    test("isrenderobj", {}, function() end)
    test("getrenderproperty", {}, function() end)
    test("setrenderproperty", {}, function() end)
    test("cleardrawcache", {}, function() end)
    test("WebSocket", {})
    test("WebSocket.connect", {}, function() end)
]]

-- 2. ระบบ Interceptor (ตัวดักจับ)
local OldLoadstring
OldLoadstring = hookfunction(getgenv().loadstring, function(chunk, chunkName)
    -- ตรวจสอบว่า Code ที่กำลังจะรัน มีคำว่า "UNC Environment Check" หรือไม่
    if type(chunk) == "string" and (string.find(chunk, "UNC Environment Check") or string.find(chunk, "UNC Summary")) then
        return OldLoadstring(Patched_UNC, "UNC")
    end
    
    return OldLoadstring(chunk, chunkName)
end)
